blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^post/(?P<pk>[0-9]+)/email_share/$', views.email_share, name='email_share'),
    url(r'^about_me/$', views.about_me, name='about_me'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

comments/urls.py
from django.conf.urls import url
from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_published_num(self):
        return self.post_set.filter(status=1).count()


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status=1)


class Post(models.Model):
    STATUS_CHOICES = (
        (0, '未发表'),
        (1, '已发表')
    )
    title = models.CharField(max_length=70, verbose_name='标题')
    body = models.TextField(verbose_name='内容')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modified_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='摘要')
    category = models.ForeignKey(Category, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签云')
    author = models.ForeignKey(User, verbose_name='作者')
    views = models.PositiveIntegerField(default=0, verbose_name='浏览数')
    status = models.IntegerField(choices=STATUS_CHOICES, default=1, verbose_name='发布状态')
    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite'])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']


class Timeline(models.Model):
    title = models.CharField(max_length=70, verbose_name='标题')
    body = models.TextField(verbose_name='内容')
    created_time = models.DateField(verbose_name='创建时间')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_time']

comments/models.py
from django.db import models

# Create your models here.


class Comment(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/forms.py
from django import forms


class EmailForm(forms.Form):
    name = forms.CharField(label='您的姓名', max_length=25)
    to = forms.EmailField(label='对方地址')
    # 加上widget=forms.Textarea以扩展为<textarea>标签，加上required=False可以不用必须输入
    comment = forms.CharField(label='附加留言', widget=forms.Textarea, required=False)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Post, Category, Tag, Timeline
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q
from .forms import EmailForm
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib import messages
from blog.tasks import sendemail


class IndexView(ListView):
    # model = Post
    queryset = Post.published.all()
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range

        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number-3) if (page_number-3)>0 else 0:page_number-1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=['markdown.extensions.extra',
                                           'markdown.extensions.codehilite',
                                           TocExtension(slugify=slugify)])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        # 相似博文推荐 TODO:这里逻辑还不清楚
        tag_list = self.object.tags.values_list('pk', flat=True)
        sim_post = Post.published.filter(tags__in=tag_list).exclude(pk=self.object.pk)
        sim_post = sim_post.annotate(same_tag=Count('tags')).order_by('-same_tag', '-created_time')[:5]
        context.update({
            'form': form,
            'comment_list': comment_list,
            'sim_post': sim_post
        })
        return context


class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def email_share(request, pk):
    post = get_object_or_404(Post, pk=pk, status=1)
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            # cleaned_data只会包含验证通过的字段
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = "{}分享给您来自 MZM's Blog 的文章:{}".format(data['name'], post.title)
            message = "文章题目：{}\n阅读地址：{} \n分享留言:{}".format(post.title, post_url, data['comment'])
            send_mail(subject, message, 'moflasky@163.com', [data['to']])
            #sendemail.delay(subject, message, [data['to']])
            messages.success(request, '邮件已发送，分享成功！')
            return redirect(post)
    else:
        form = EmailForm()
    return render(request, 'blog/emailshare.html', {'form': form, 'post': post})


def about_me(request):
    timelines = Timeline.objects.all()
    return render(request, 'blog/aboutme.html', {'timelines': timelines})

templates/blog/aboutme.html
{% extends 'base.html' %}
{% block title %}首页{% endblock title %}

{% block pagehead %}
    <h1 class="blog-title">时间线</h1>
    <p class="lead blog-description">一步一个脚印</p>
{% endblock pagehead %}


{% block main %}
    <section id="cd-timeline" class="cd-container">
	<div class="cd-timeline-block">
		<div class="cd-timeline-icon">
			<i class="ion-clock"></i>
		</div>
		<div class="cd-timeline-content">
			<h2><strong>未来</strong></h2>
			<p>未完待续。</p>
			<span class="cd-date">2017年—</span>
		</div>
	</div>
	{% for tl in timelines %}
    <div class="cd-timeline-block">
		<div class="cd-timeline-icon">
			<i class="ion-clock"></i>
		</div>
		<div class="cd-timeline-content">
			<h2><strong>{{ tl.title }}</strong></h2>
			<p>{{ tl.body }}</p>
			<span class="cd-date">{{ tl.created_time }}</span>
		</div>
	</div>
    {% endfor %}
{#	<div class="cd-timeline-block">#}
{#		<div class="cd-timeline-icon">#}
{#			<i class="ion-clock"></i>#}
{#		</div>#}
{#		<div class="cd-timeline-content">#}
{#			<h2><strong>相似文章推荐功能</strong></h2>#}
{#			<p>增加 相似文章推荐 功能。能根据相同标签的个数，找出相似文章。</p>#}
{#			<span class="cd-date">2017年8月25日</span>#}
{#		</div>#}
{#	</div>#}
{#	<div class="cd-timeline-block">#}
{#		<div class="cd-timeline-icon">#}
{#			<i class="ion-clock"></i>#}
{#		</div>#}
{#		<div class="cd-timeline-content">#}
{#			<h2><strong>部署上线</strong></h2>#}
{#			<p>实现基本博客功能，上线，部署至阿里云。</p>#}
{#			<span class="cd-date">2017年8月22日</span>#}
{#		</div>#}
{#	</div>#}
{#	<div class="cd-timeline-block">#}
{#		<div class="cd-timeline-icon">#}
{#			<i class="ion-clock"></i>#}
{#		</div>#}
{#		<div class="cd-timeline-content">#}
{#			<h2><strong>起步</strong></h2>#}
{#			<p>开始学习Django，从零开始开发。</p>#}
{#			<span class="cd-date">2017年8月</span>#}
{#		</div>#}
{#	</div>#}
</section>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}文章详情：{{ post.title }}{% endblock title %}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <div class="post-head">
            <h1 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
            <div class="post-meta">
                <span class="author">作者：{{ post.author }}</span>
                <time class="post-date" datetime="{{ post.created_time }}"> {{ post.created_time }}</time>
                <span> {{ post.comment_set.count }} 评论</span>
                <span> {{ post.views }} 阅读</span>
            </div>
        </div>
        <div class="post-content clearfix">
            {{ post.body | safe }}
        </div>
        <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
                分类 :<a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
            </div>
            <div class="pull-right tag-list">
                Tag : {% for tag in post.tags.all %}<a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>{% endfor %}
            </div>
        </footer>
        <br/>
        <P><a href="{% url 'blog:email_share' post.pk %}">通过邮件分享这篇文章</a></P>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="form-horizontal">
            {% csrf_token %}
            <fieldset>
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}" class="col-lg-2 control-label">名字：</label>
                <div class="col-lg-5">
                    <input type="text" class="form-control" name="name">
                    {{ form.name.errors }}
                </div>
            </div>
            <div class="form-group">
                <label for="{{ form.text.id_for_label }}" class="col-lg-2 control-label">评论：</label>
                <div class="col-lg-10">
                    <textarea class="form-control" rows="5" name="text"></textarea>
                    {{ form.text.errors }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                    <button type="submit" class="btn btn-primary">发表</button>
                </div>
            </div>
            </fieldset>
        </form>
        <br/>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                {% for comment in comment_list %}
                <div class="panel panel-default">
                    <div class="panel-heading">{{ forloop.counter }}. {{ comment.name }}： <span class="pull-right">{{ comment.created_time }}</span></div>
                    <div class="panel-body">
                        {{ comment.text }}
                    </div>
                </div>
                {% empty %}
                暂无评论！
                {% endfor %}
        </div>
    </section>
{% endblock main %}
{% block toc %}
<div class="widget">
    <h3 class="title">文章目录</h3>
        {{ post.toc | safe }}
</div>
<div class="widget">
    <h3 class="title">相关文章推荐</h3>
    <ul>
        {% for post in sim_post %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% empty %}
        暂无相关文章！
        {% endfor %}
    </ul>
</div>
{% endblock toc %}

templates/blog/emailshare.html
{% extends 'base.html' %}
{% block title %}首页{% endblock title %}

{% block pagehead %}
    <h1 class="blog-title">通过电子邮件分享《{{ post.title }}》</h1>
    <p class="lead blog-description">输入您的名字及对方的Email地址，还可以附加留言。</p>
{% endblock pagehead %}

{% block main %}
    <form action="{% url 'blog:email_share' post.pk %}" method="post" class="form-horizontal">
        {% csrf_token %}
        <fieldset>
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" class="col-lg-2 control-label">名字：</label>
            <div class="col-lg-5">
                <input type="text" class="form-control" name="name">
                {{ form.name.errors }}
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.to.id_for_label }}" class="col-lg-2 control-label">对方地址：</label>
            <div class="col-lg-5">
                <input type="text" class="form-control" name="to">
                {{ form.to.errors }}
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.comment.id_for_label }}" class="col-lg-2 control-label">附加留言：</label>
            <div class="col-lg-10">
                <textarea class="form-control" rows="5" name="comment"></textarea>
                {{ form.comment.errors }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary">发表</button>
            </div>
        </div>
        </fieldset>
    </form>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock title %}

{% block pagehead %}
    <h1 class="blog-title">欢迎来到我的博客</h1>
    <p class="lead blog-description">这里记录着进步的点点滴滴</p>
{% endblock pagehead %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
    <article id={{ post.pk }} class="post">
        <div class="post-head">
            <h1 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
            <div class="post-meta">
                <span class="author">作者：{{ post.author }}</span>
                <time class="post-date" datetime="{{ post.created_time }}"> {{ post.created_time }}</time>
                <span> {{ post.comment_set.count }} 评论</span>
                <span> {{ post.views }} 阅读</span>
            </div>
        </div>
        <div class="post-content">
            <p>{{ post.excerpt }} ...</p>
        </div>
        <div>
            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">阅读全文</a>
        </div>
        <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
                分类 :<a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
            </div>
            <div class="pull-right tag-list">
                Tag : {% for tag in post.tags.all %}<a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>{% endfor %}
            </div>
        </footer>
    </article>
    {% empty %}
        <div class="no-post">暂时还没有文章</div>
    {% endfor %}
    {%  if is_paginated %}
    <ul class="pagination">
        <li{% if not page_obj.has_previous %} class="disabled"{% endif %}>
            <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}">
                &laquo;
            </a>
        </li>
    {% if first %}
        <li><a href="?page=1">1</a></li>
    {% endif %}
    {% if left %}
        {% if left_has_more %}
            <li><span>...</span></li>
        {% endif %}
        {% for i in left %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
    {% endif %}
    <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
    {% if right %}
        {% for i in right %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        {% if right_has_more %}
            <li><span>...</span></li>
        {% endif %}
    {% endif %}
    {% if last %}
        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
    {% endif %}
        <li{% if not page_obj.has_next %} class="disabled"{% endif %}>
            <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
    {% endif %}
{% endblock %}