blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^post/(?P<pk>[0-9]+)/email_share/$', views.email_share, name='email_share'),
    url(r'^about_me/$', views.about_me, name='about_me'),
]

blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>MZM's Blog - {% block title %}{% endblock title %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/timelinestyle.css' %}">

    <!-- icon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="icon">

    <style>
        span.highlighted {
            color: red;
        }
    </style>
</head>

<body class="home-template">
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">MZM's Blog</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'blog:index' %}">首页</a></li>
{#                    <li><a href="#">博客</a></li>#}
                    <li><a href="{% url 'blog:about_me' %}">关于</a></li>
{#                    <li><a href="#">联系</a></li>#}
                </ul>
                <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}" class="navbar-form navbar-right">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="search" name="q" placeholder="关键字搜索" required class="form-control">
                            <span class="input-group-btn">
                            <button type="submit" class="btn btn-default"><span class="ion-ios-search-strong"></span></button>
                            </span>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </nav>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
    <div class="blog-header">
    {% block pagehead %}
    {% endblock pagehead %}
    </div>
    <div class="row">
        <main class="col-md-8 blog-main">
            {% block main %}
            {% endblock main %}
        </main>
        <aside class="col-md-4 sidebar">
            {% block toc %}
            {% endblock toc %}
            <div class="widget">
                <h3 class="title">最新文章</h3>
                {% get_recent_posts as recent_post_list %}
                <ul>
                    {% for post in recent_post_list %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                    {% empty %}
                    暂无文章！
                    {% endfor %}
                </ul>
            </div>

            <div class="widget">
                <h3 class="title">归档</h3>
                {% archives as date_list %}
                <ul>
                    {% for date in date_list %}
                    <li>
                        <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                    </li>
                    {% empty %}
                    暂无归档！
                    {% endfor %}
                </ul>
            </div>

            <div class="widget">
                <h3 class="title">分类</h3>
                {% get_categories as category_list %}
                <ul>
                    {% for category in category_list %}
                    <li>
                        <a href="{% url 'blog:category' category.pk %}">{{ category.name }}
                            <span class="post-count">({{ category.get_published_num }})</span>
                        </a>
                    </li>
                    {% empty %}
                    暂无分类！
                    {% endfor %}
                </ul>
            </div>

            <div class="widget widget-tag-cloud">
                <h3 class="title">标签云</h3>
                {% get_tags as tag_list %}
                {% for tag in tag_list %}
                    <span class="label label-primary"><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></span>
                {% empty %}
                暂无标签！
                {% endfor %}
            </div>
            <div class="rss">
                <a href="{% url 'rss' %}"><span class="ion-social-rss"></span> RSS 订阅本博客</a>
            </div>
        </aside>
    </div>
    <footer class="footer footer-copyright">
        <div class="row">
            <div class="col-md-12">
                <span class="pull-right" ><a href="#top"><i class="ion-arrow-up-c"></i> 回到顶部</a></span>
                <p class="copyright">
                    Copyright &copy 2017 - MZM's Blog
                </p>
            </div>
        </div>
    </footer>
</div>
<script src="http://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>